blocks:
  default: >-
    [
      {
        "name": "Tag Topics",
        "params": [
          {
            "name": "tag",
            "value": "announcement"
          }
        ]
      },
      {
        "name": "minimal-gamification-leaderboard",
        "params": [
          {
            "name": "id",
            "value": "1"
          }
        ]
      }
    ]

  json_schema: >-
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "params": {
            "type": "array",
            "format": "table",
            "uniqueItems": true,
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
show_in_routes:
  type: list
  list_type: "simple"
  default: "discovery.categories"
  description: "Advanced users only: limit sidebar to the selected routes. <br/><br/>Examples: discovery.latest, discovery.unread, discovery.new, discovery.top, tag.show, \"c/category-slug\" (for categories), \"tag/sample-tag\" (for tags). <br/><br/>When empty, the sidebar is shown on all list routes."
  allow_any: true
  choices:
